<?php
namespace DDTrace\Transport\Jaeger\Thrift\Agent\Zipkin;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface ZipkinCollectorIf
{
    /**
     * @param \DDTrace\Transport\Jaeger\Thrift\Agent\Zipkin\Span[] $spans
     * @return \DDTrace\Transport\Jaeger\Thrift\Agent\Zipkin\Response[]
     */
    public function submitZipkinBatch(array $spans);
}
