<?php
namespace DDTrace\Transport\Jaeger\Thrift\Agent;

/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface AgentIf
{
    /**
     * @param \DDTrace\Transport\Jaeger\Thrift\Agent\Zipkin\Span[] $spans
     */
    public function emitZipkinBatch(array $spans);
    /**
     * @param \DDTrace\Transport\Jaeger\Thrift\Batch $batch
     */
    public function emitBatch(\DDTrace\Transport\Jaeger\Thrift\Batch $batch);
}
